In [1]:
# Unita: One-hot encoding

## Codifica One-hot encoding usando scikit-learn

In [2]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [4]:
# vettore in input
v = ['rosso', 'rosso', 'bianco', 'nero', 'bianco', 'nero', 'nero']

In [5]:
# da list a array
a = array(v)

In [6]:
# integer encoder 
le = LabelEncoder()
iv = le.fit_transform(a)
print(iv)

[2 2 0 1 0 1 1]


In [14]:
# one-hot encoder
oe = OneHotEncoder(sparse=False)
# converto l'array N-dim in matrice N-dim x 1
iv = iv.reshape(len(iv), 1)
bv = oe.fit_transform(iv)
print(bv)

[[ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]]
